name: CI
on:
  push:
  repository_dispatch:
    types: ci
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            .pnpmfile.cjs
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install FE dependencies
        run: pnpm install --frozen-lockfile

      - name: Run FE typecheck
        run: pnpm typecheck

      - name: Run FE lint
        run: pnpm lint
